export const INDIAN_STATES = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
];

export const ODISHA_DISTRICT_BLOCKS: Record<string, string[]> = {
  "Angul": ["Angul", "Athmallik", "Banarpal", "Chhendipada", "Kishorenagar", "Pallahara", "Kaniha", "Talcher"],
  "Balangir": ["Agalpur", "Balangir", "Bangomunda", "Belpara", "Deogaon", "Gudvella", "Khaprakhol", "Loisingha", "Muribahal", "Patnagarh", "Puintala", "Saintala", "Titilagarh", "Turekela"],
  "Baleswar": ["Bahanaga", "Baleswar", "Baliapal", "Basta", "Bhograi", "Jaleswar", "Khaira", "Nilagiri", "Oupada", "Remuna", "Simulia", "Soro"],
  "Bargarh": ["Ambabhona", "Attabira", "Bargarh", "Barpali", "Bhatli", "Bheden", "Bijepur", "Gaisilet", "Jharbandh", "Padampur", "Paikmal", "Rajborasambar"],
  "Bhadrak": ["Bhadrak", "Bhandaripokhari", "Basudevpur", "Bonth", "Chandabali", "Dihidi", "Tihidi"],
  "Boudh": ["Boudh", "Harabhanga", "Kantamal"],
  "Cuttack": ["Athagarh", "Badamba", "Banki", "Banki Dampada", "Barang", "Cuttack Sadar", "Kantapada", "Mahanga", "Niali", "Nischintakoili", "Salepur", "Tangi-Choudwar", "Tigiria"],
  "Deogarh": ["Barkote", "Reamal", "Tileibani"],
  "Dhenkanal": ["Bhuban", "Dhenkanal", "Gondia", "Hindol", "Kamakhyanagar", "Kankadahad", "Odapada", "Parjang"],
  "Gajapati": ["Gumma", "Kashinagar", "Mohana", "Nuagada", "Paralakhemundi", "R.Udayagiri", "Rayagada"],
  "Ganjam": ["Aska", "Beguniapada", "Bellaguntha", "Bhanjanagar", "Buguda", "Chhatrapur", "Chikiti", "Dharakote", "Digapahandi", "Ganjam", "Hinjilicut", "Jagannathprasad", "Kabisuryanagar", "Khallikote", "Kukudakhandi", "Patrapur", "Polasara", "Purushottampur", "Rangeilunda", "Sanakhemundi", "Sheragada", "Surada"],
  "Jagatsinghapur": ["Balikuda", "Biridi", "Erasama", "Jagatsinghapur", "Kujang", "Naugaon", "Raghunathpur", "Tirtol"],
  "Jajpur": ["Bari", "Binjharpur", "Danagadi", "Dasarathpur", "Dharmasala", "Jajpur", "Korai", "Rasulpur", "Sukinda"],
  "Jharsuguda": ["Jharsuguda", "Kirmira", "Kolabira", "Laikera", "Lakhanpur"],
  "Kalahandi": ["Bhawanipatna", "Dharmagarh", "Golamunda", "Jaipatna", "Junagarh", "Kalampur", "Karlamunda", "Kesinga", "Koksara", "Lanjigarh", "M.Rampur", "Narla", "Th.Rampur"],
  "Kandhamal": ["Balliguda", "Chakapada", "Daringbadi", "G.Udayagiri", "Khajuripada", "Kotagarh", "Nuagaon", "Phiringia", "Phulbani", "Raikia", "Tikabali", "Tumudibandha"],
  "Kendrapara": ["Aul", "Derabish", "Garadpur", "Kendrapara", "Mahakalapada", "Marshaghai", "Pattamundai", "Rajkanika", "Rajnagar"],
  "Kendujhar": ["Anandapur", "Bansapal", "Champua", "Ghasipura", "Ghatgaon", "Hatia", "Jhumpura", "Joda", "Keonjhar", "Patna", "Saharpada", "Telkoi"],
  "Khordha": ["Balianta", "Balipatna", "Banapur", "Bhubaneswar", "Bolagarh", "Chilika", "Jatni", "Khurda", "Tangi"],
  "Koraput": ["Bandhugaon", "Borigumma", "Dasamantapur", "Jeypore", "Kundra", "Koraput", "Kotpad", "Laxmipur", "Nandapur", "Narayanapatna", "Pottangi", "Semiliguda", "Bhairasingpur", "Boipariguda"],
  "Malkangiri": ["Chitrakonda", "Kalimela", "Khairput", "Korkunda", "Malkangiri", "Mathili", "Podia"],
  "Mayurbhanj": ["Badasahi", "Bahalda", "Bangiriposi", "Baripada", "Betnoti", "Bijatala", "Bisoi", "Gopabandhunagar", "Jamda", "Jashipur", "Kaptipada", "Karanjia", "Khunta", "Kusumi", "Morada", "Rairangpur", "Raruan", "Rasgovindpur", "Samakhunta", "Sarat", "Saraskana", "Shyamakhunta", "Suliapada", "Thakurmunda", "Tiring", "Udala"],
  "Nabarangpur": ["Chandahandi", "Dabugam", "Jharigam", "Kosagumuda", "Nabarangpur", "Nandahandi", "Papahandi", "Raighar", "Tentulikhunti", "Umerkote"],
  "Nayagarh": ["Bhapur", "Dasapalla", "Gania", "Khandapada", "Nayagarh", "Nuagaon", "Odagaon", "Ranpur"],
  "Nuapada": ["Boden", "Khariar", "Komna", "Nuapada", "Sinapali"],
  "Puri": ["Astaranga", "Brahmagiri", "Delanga", "Gop", "Kakatpur", "Kanas", "Krushnaprasad", "Nimapada", "Pipili", "Puri Sadar", "Satyabadi"],
  "Rayagada": ["Bissamcuttack", "Chandrapur", "Gudari", "Gunupur", "Kalyansingpur", "Kashipur", "Kolnara", "Muniguda", "Padmapur", "Ramaguda", "Rayagada"],
  "Sambalpur": ["Bamra", "Dhankauda", "Jamankira", "Jujomura", "Kuchinda", "Maneswar", "Naktideul", "Rairakhol", "Rengali"],
  "Sonepur": ["Binka", "Dunguripali", "Sonepur", "Tarbha", "Ullunda", "Birmaharajpur"],
  "Sundargarh": ["Balisankara", "Bargaon", "Bisma", "Banei", "Gurundia", "Hemgir", "Koida", "Kuarmunda", "Kutra", "Lahunipara", "Lathikata", "Lephripara", "Nuagaon", "Rajgangpur", "Subdega", "Sundargarh", "Tangarpali"]
};

export const ODISHA_DISTRICTS = Object.keys(ODISHA_DISTRICT_BLOCKS).sort();
export const WEAVER_DISTRICTS = ["Bargarh", "Sonepur", "Sambalpur", "Boudh", "Nuapada", "Balangir", "Kalahandi"];
